name: ci
on:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10', '3.x' ]
    name: test with ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          cd checks.d
          python3 -m venv .venv
          .venv/bin/pip3 install -r requirements-dev.lock
          env PYTHONPATH=. .venv/bin/python3 -m unittest test_custom_dd_agent_status.py
